source 'https://rubygems.org'
gem 'rails', '~> 5.2.3'

gem 'pg', '~> 0.18.2'
gem 'sassc-rails', '~> 2.1.2'
gem 'uglifier', '>= 1.3.0'
gem 'jbuilder', '~> 2.0'
gem 'yajl-ruby', '~> 1.3.1', require: 'yajl'
gem 'multi_json', '~> 1.10.1'
gem 'kaminari', '~> 1.2.1'
gem 'audited', '~> 4.9'
gem 'diffy', '~> 3.3.0'
gem 'pundit', '2.1.0'
gem 'acts_as_commentable', '~> 4.0.2'
gem 'activeadmin', '~> 1.4.3'
gem 'daemons', '~> 1.2.5'
gem 'obo', '~> 0.1.5'
gem 'gravatarify', '~> 3.0.0'
gem 'slodown', '~> 0.4.0'
gem 'scenic', '~> 1.5.1'
gem 'awesome_nested_set', '~> 3.1.4'
gem 'staccato', '~> 0.5.3'
gem 'rack-rewrite'
gem 'paperclip', '~> 6.1.0'
gem 'rack-cors', '~> 1.0.5', require: 'rack/cors'
gem 'htmlentities'
gem 'rack-attack', '~> 6.0.0'

gem 'sidekiq', '~> 6.0.3'
gem 'sidekiq-cron', '~> 1.1.0'

gem 'airbrake', '~> 10.0.5'

gem 'omniauth', '~> 1.9.0'
gem 'omniauth-github', '~> 1.4.0'
gem 'omniauth-google-oauth2', '~> 0.7.0'
gem 'omniauth-orcid', '~> 2.1.1'

gem 'aws-sdk-s3', '~> 1.94.0'

group :test, :development do
  gem 'rspec-rails'
  gem 'fabrication'
  gem 'capybara'
  gem 'launchy'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'database_cleaner'
  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'simplecov'
  gem 'simplecov-lcov'
end

group :development do
  gem 'rack-mini-profiler'
  gem 'capistrano', '~> 3.10.0'
  gem 'capistrano-rails', '~> 1.4'
  gem 'capistrano-rbenv', '~> 2.0'
  gem 'capistrano-passenger', '~> 0.2.0'
end
