source 'https://rubygems.org'
gem 'rails', '~> 4.2.0'

gem 'pg', '~> 0.18.2'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'libv8', '~> 3.16.14.7'
gem 'therubyracer', '~> 0.12.1', platforms: :ruby
gem 'jbuilder', '~> 2.0'
gem 'yajl-ruby', '~> 1.2.1', require: 'yajl'
gem 'multi_json', '~> 1.10.1'
gem 'kaminari', '~> 0.16.1'
gem 'audited-activerecord', '~> 4.0'
gem 'diffy', '~> 3.0.7'
gem 'pundit', '~> 1.0.0'
gem 'acts_as_commentable', '~> 4.0.2'
gem 'activeadmin', github: 'activeadmin'
gem 'delayed_job_active_record', '~> 4.0.3'
gem 'daemons', '~> 1.2.5'
gem 'obo', '~> 0.1.5'
gem 'gravatarify', '~> 3.0.0'
gem 'slodown', '~> 0.1.3'
gem 'scenic', '~> 1.2.0'
gem 'awesome_nested_set', '~> 3.1.1'
gem 'staccato', '~> 0.4.7'
gem 'rack-rewrite'
gem 'paperclip', '~> 5.1.0'
gem 'rack-cors', '~> 1.0.2', require: 'rack/cors'

gem 'omniauth', '~> 1.8.1'
gem 'omniauth-facebook', '~> 1.6.0'
gem 'omniauth-github', '~> 1.1.2'
gem 'omniauth-google-oauth2', '~> 0.2.5'
gem 'omniauth-orcid', '~> 2.1.1'

group :test, :development do
  gem 'rspec-rails'
  gem 'fabrication'
  gem 'capybara'
  gem 'launchy'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'database_cleaner'
  gem 'pry'
  gem 'pry-remote'
  gem 'pry-nav'
  gem 'pry-rails'
  gem 'coveralls', require: false
end

group :development do
  gem 'rack-mini-profiler'
  gem 'capistrano', '~> 3.9.0'
  gem 'capistrano-rails', '~> 1.3'
  gem 'capistrano-rbenv', '~> 2.0'
  gem 'capistrano-passenger', '~> 0.2.0'
  gem 'capistrano3-delayed-job', '~> 1.7.5'
end
