# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ga4gh/common.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "ga4gh.GAException" do
    optional :error_code, :int32, 1
    optional :message, :string, 2
  end
  add_message "ga4gh.Position" do
    optional :reference_name, :string, 1
    optional :position, :int64, 2
    optional :strand, :enum, 3, "ga4gh.Strand"
  end
  add_message "ga4gh.ExternalIdentifier" do
    optional :database, :string, 1
    optional :identifier, :string, 2
    optional :version, :string, 3
  end
  add_enum "ga4gh.Strand" do
    value :STRAND_UNSPECIFIED, 0
    value :NEG_STRAND, 1
    value :POS_STRAND, 2
  end
end

module Ga4gh
  GAException = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh.GAException").msgclass
  Position = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh.Position").msgclass
  ExternalIdentifier = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh.ExternalIdentifier").msgclass
  Strand = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh.Strand").enummodule
end
