# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ga4gh/genotype_phenotype_service.proto

require 'google/protobuf'

require 'ga4gh/common'
require 'ga4gh/metadata'
require 'ga4gh/genotype_phenotype'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "ga4gh.SearchPhenotypeAssociationSetsRequest" do
    optional :dataset_id, :string, 1
    optional :page_size, :int64, 2
    optional :page_token, :string, 3
  end
  add_message "ga4gh.SearchPhenotypeAssociationSetsResponse" do
    repeated :phenotype_association_sets, :message, 1, "ga4gh.PhenotypeAssociationSet"
    optional :next_page_token, :string, 2
  end
  add_message "ga4gh.OntologyTermQuery" do
    repeated :terms, :message, 1, "ga4gh.OntologyTerm"
  end
  add_message "ga4gh.ExternalIdentifierQuery" do
    repeated :ids, :message, 1, "ga4gh.ExternalIdentifier"
  end
  add_message "ga4gh.EvidenceQuery" do
    optional :evidenceType, :message, 1, "ga4gh.OntologyTerm"
    optional :description, :string, 2
    repeated :external_identifiers, :message, 3, "ga4gh.ExternalIdentifier"
  end
  add_message "ga4gh.SearchPhenotypesRequest" do
    optional :phenotype_association_set_id, :string, 1
    optional :id, :string, 2
    optional :description, :string, 3
    optional :type, :message, 4, "ga4gh.OntologyTerm"
    repeated :qualifiers, :message, 5, "ga4gh.OntologyTerm"
    optional :age_of_onset, :message, 6, "ga4gh.OntologyTerm"
    optional :page_size, :int64, 7
    optional :page_token, :string, 8
  end
  add_message "ga4gh.SearchPhenotypesResponse" do
    repeated :phenotypes, :message, 1, "ga4gh.PhenotypeInstance"
    optional :next_page_token, :string, 2
  end
  add_message "ga4gh.SearchGenotypePhenotypeRequest" do
    optional :phenotype_association_set_id, :string, 1
    repeated :feature_ids, :string, 2
    repeated :phenotype_ids, :string, 3
    repeated :evidence, :message, 4, "ga4gh.EvidenceQuery"
    optional :page_size, :int64, 5
    optional :page_token, :string, 6
  end
  add_message "ga4gh.SearchGenotypePhenotypeResponse" do
    repeated :associations, :message, 1, "ga4gh.FeaturePhenotypeAssociation"
    optional :next_page_token, :string, 2
  end
end

module Ga4gh
  SearchPhenotypeAssociationSetsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh.SearchPhenotypeAssociationSetsRequest").msgclass
  SearchPhenotypeAssociationSetsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh.SearchPhenotypeAssociationSetsResponse").msgclass
  OntologyTermQuery = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh.OntologyTermQuery").msgclass
  ExternalIdentifierQuery = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh.ExternalIdentifierQuery").msgclass
  EvidenceQuery = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh.EvidenceQuery").msgclass
  SearchPhenotypesRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh.SearchPhenotypesRequest").msgclass
  SearchPhenotypesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh.SearchPhenotypesResponse").msgclass
  SearchGenotypePhenotypeRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh.SearchGenotypePhenotypeRequest").msgclass
  SearchGenotypePhenotypeResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh.SearchGenotypePhenotypeResponse").msgclass
end
