# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ga4gh/genotype_phenotype.proto

require 'google/protobuf'

require 'ga4gh/metadata'
require 'google/protobuf/struct'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "ga4gh.PhenotypeAssociationSet" do
    optional :id, :string, 1
    optional :name, :string, 2
    optional :dataset_id, :string, 3
    map :info, :string, :message, 4, "google.protobuf.ListValue"
  end
  add_message "ga4gh.EnvironmentalContext" do
    optional :id, :string, 1
    optional :environment_type, :message, 2, "ga4gh.OntologyTerm"
    optional :description, :string, 3
  end
  add_message "ga4gh.PhenotypeInstance" do
    optional :id, :string, 1
    optional :type, :message, 2, "ga4gh.OntologyTerm"
    repeated :qualifier, :message, 3, "ga4gh.OntologyTerm"
    optional :age_of_onset, :message, 4, "ga4gh.OntologyTerm"
    optional :description, :string, 5
    map :info, :string, :message, 6, "google.protobuf.ListValue"
  end
  add_message "ga4gh.Evidence" do
    optional :evidence_type, :message, 1, "ga4gh.OntologyTerm"
    optional :description, :string, 2
    map :info, :string, :message, 3, "google.protobuf.ListValue"
  end
  add_message "ga4gh.FeaturePhenotypeAssociation" do
    optional :id, :string, 1
    optional :phenotype_association_set_id, :string, 2
    repeated :feature_ids, :string, 3
    repeated :evidence, :message, 4, "ga4gh.Evidence"
    optional :phenotype, :message, 5, "ga4gh.PhenotypeInstance"
    optional :description, :string, 6
    repeated :environmental_contexts, :message, 7, "ga4gh.EnvironmentalContext"
    map :info, :string, :message, 8, "google.protobuf.ListValue"
  end
end

module Ga4gh
  PhenotypeAssociationSet = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh.PhenotypeAssociationSet").msgclass
  EnvironmentalContext = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh.EnvironmentalContext").msgclass
  PhenotypeInstance = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh.PhenotypeInstance").msgclass
  Evidence = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh.Evidence").msgclass
  FeaturePhenotypeAssociation = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh.FeaturePhenotypeAssociation").msgclass
end
