#!/bin/bash
set -e

case "$1" in
    configure)
      chown -R www-data /var/www/docm/
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac
