class AddCountryToUsers < ActiveRecord::Migration[4.2]
  def change
    create_table :countries do |t|
      t.text :iso, null: false
      t.text :name, null: false
      t.timestamp
    end
    add_reference :users, :country, index: true

    Country.reset_column_information
    Country.create(:iso => 'AF', :name => 'Afghanistan') 
    Country.create(:iso => 'AL', :name => 'Albania') 
    Country.create(:iso => 'DZ', :name => 'Algeria') 
    Country.create(:iso => 'AS', :name => 'American Samoa') 
    Country.create(:iso => 'AD', :name => 'Andorra') 
    Country.create(:iso => 'AO', :name => 'Angola') 
    Country.create(:iso => 'AI', :name => 'Anguilla') 
    Country.create(:iso => 'AG', :name => 'Antigua and Barbuda') 
    Country.create(:iso => 'AR', :name => 'Argentina') 
    Country.create(:iso => 'AM', :name => 'Armenia') 
    Country.create(:iso => 'AW', :name => 'Aruba') 
    Country.create(:iso => 'AU', :name => 'Australia') 
    Country.create(:iso => 'AT', :name => 'Austria') 
    Country.create(:iso => 'AZ', :name => 'Azerbaijan') 
    Country.create(:iso => 'BS', :name => 'Bahamas') 
    Country.create(:iso => 'BH', :name => 'Bahrain') 
    Country.create(:iso => 'BD', :name => 'Bangladesh') 
    Country.create(:iso => 'BB', :name => 'Barbados') 
    Country.create(:iso => 'BY', :name => 'Belarus') 
    Country.create(:iso => 'BE', :name => 'Belgium') 
    Country.create(:iso => 'BZ', :name => 'Belize') 
    Country.create(:iso => 'BJ', :name => 'Benin') 
    Country.create(:iso => 'BM', :name => 'Bermuda') 
    Country.create(:iso => 'BT', :name => 'Bhutan') 
    Country.create(:iso => 'BO', :name => 'Bolivia') 
    Country.create(:iso => 'BA', :name => 'Bosnia and Herzegovina') 
    Country.create(:iso => 'BW', :name => 'Botswana') 
    Country.create(:iso => 'BR', :name => 'Brazil') 
    Country.create(:iso => 'BN', :name => 'Brunei Darussalam') 
    Country.create(:iso => 'BG', :name => 'Bulgaria') 
    Country.create(:iso => 'BF', :name => 'Burkina Faso') 
    Country.create(:iso => 'BI', :name => 'Burundi') 
    Country.create(:iso => 'KH', :name => 'Cambodia') 
    Country.create(:iso => 'CM', :name => 'Cameroon') 
    Country.create(:iso => 'CA', :name => 'Canada') 
    Country.create(:iso => 'CV', :name => 'Cape Verde') 
    Country.create(:iso => 'KY', :name => 'Cayman Islands') 
    Country.create(:iso => 'CF', :name => 'Central African Republic') 
    Country.create(:iso => 'TD', :name => 'Chad') 
    Country.create(:iso => 'CL', :name => 'Chile') 
    Country.create(:iso => 'CN', :name => 'China') 
    Country.create(:iso => 'CO', :name => 'Colombia') 
    Country.create(:iso => 'KM', :name => 'Comoros') 
    Country.create(:iso => 'CG', :name => 'Congo') 
    Country.create(:iso => 'CD', :name => 'Congo, the Democratic Republic of the') 
    Country.create(:iso => 'CK', :name => 'Cook Islands') 
    Country.create(:iso => 'CR', :name => 'Costa Rica') 
    Country.create(:iso => 'CI', :name => 'Cote D\'Ivoire') 
    Country.create(:iso => 'HR', :name => 'Croatia') 
    Country.create(:iso => 'CU', :name => 'Cuba') 
    Country.create(:iso => 'CY', :name => 'Cyprus') 
    Country.create(:iso => 'CZ', :name => 'Czech Republic') 
    Country.create(:iso => 'DK', :name => 'Denmark') 
    Country.create(:iso => 'DJ', :name => 'Djibouti') 
    Country.create(:iso => 'DM', :name => 'Dominica') 
    Country.create(:iso => 'DO', :name => 'Dominican Republic') 
    Country.create(:iso => 'EC', :name => 'Ecuador') 
    Country.create(:iso => 'EG', :name => 'Egypt') 
    Country.create(:iso => 'SV', :name => 'El Salvador') 
    Country.create(:iso => 'GQ', :name => 'Equatorial Guinea') 
    Country.create(:iso => 'ER', :name => 'Eritrea') 
    Country.create(:iso => 'EE', :name => 'Estonia') 
    Country.create(:iso => 'ET', :name => 'Ethiopia') 
    Country.create(:iso => 'FK', :name => 'Falkland Islands (Malvinas)') 
    Country.create(:iso => 'FO', :name => 'Faroe Islands') 
    Country.create(:iso => 'FJ', :name => 'Fiji') 
    Country.create(:iso => 'FI', :name => 'Finland') 
    Country.create(:iso => 'FR', :name => 'France') 
    Country.create(:iso => 'GF', :name => 'French Guiana') 
    Country.create(:iso => 'PF', :name => 'French Polynesia') 
    Country.create(:iso => 'GA', :name => 'Gabon') 
    Country.create(:iso => 'GM', :name => 'Gambia') 
    Country.create(:iso => 'GE', :name => 'Georgia') 
    Country.create(:iso => 'DE', :name => 'Germany') 
    Country.create(:iso => 'GH', :name => 'Ghana') 
    Country.create(:iso => 'GI', :name => 'Gibraltar') 
    Country.create(:iso => 'GR', :name => 'Greece') 
    Country.create(:iso => 'GL', :name => 'Greenland') 
    Country.create(:iso => 'GD', :name => 'Grenada') 
    Country.create(:iso => 'GP', :name => 'Guadeloupe') 
    Country.create(:iso => 'GU', :name => 'Guam') 
    Country.create(:iso => 'GT', :name => 'Guatemala') 
    Country.create(:iso => 'GN', :name => 'Guinea') 
    Country.create(:iso => 'GW', :name => 'Guinea-Bissau') 
    Country.create(:iso => 'GY', :name => 'Guyana') 
    Country.create(:iso => 'HT', :name => 'Haiti') 
    Country.create(:iso => 'VA', :name => 'Holy See (Vatican City State)') 
    Country.create(:iso => 'HN', :name => 'Honduras') 
    Country.create(:iso => 'HK', :name => 'Hong Kong') 
    Country.create(:iso => 'HU', :name => 'Hungary') 
    Country.create(:iso => 'IS', :name => 'Iceland') 
    Country.create(:iso => 'IN', :name => 'India') 
    Country.create(:iso => 'ID', :name => 'Indonesia') 
    Country.create(:iso => 'IR', :name => 'Iran, Islamic Republic of') 
    Country.create(:iso => 'IQ', :name => 'Iraq') 
    Country.create(:iso => 'IE', :name => 'Ireland') 
    Country.create(:iso => 'IL', :name => 'Israel') 
    Country.create(:iso => 'IT', :name => 'Italy') 
    Country.create(:iso => 'JM', :name => 'Jamaica') 
    Country.create(:iso => 'JP', :name => 'Japan') 
    Country.create(:iso => 'JO', :name => 'Jordan') 
    Country.create(:iso => 'KZ', :name => 'Kazakhstan') 
    Country.create(:iso => 'KE', :name => 'Kenya') 
    Country.create(:iso => 'KI', :name => 'Kiribati') 
    Country.create(:iso => 'KP', :name => 'Korea, Democratic People\'s Republic of') 
    Country.create(:iso => 'KR', :name => 'Korea, Republic of') 
    Country.create(:iso => 'KW', :name => 'Kuwait') 
    Country.create(:iso => 'KG', :name => 'Kyrgyzstan') 
    Country.create(:iso => 'LA', :name => 'Lao People\'s Democratic Republic') 
    Country.create(:iso => 'LV', :name => 'Latvia') 
    Country.create(:iso => 'LB', :name => 'Lebanon') 
    Country.create(:iso => 'LS', :name => 'Lesotho') 
    Country.create(:iso => 'LR', :name => 'Liberia') 
    Country.create(:iso => 'LY', :name => 'Libyan Arab Jamahiriya') 
    Country.create(:iso => 'LI', :name => 'Liechtenstein') 
    Country.create(:iso => 'LT', :name => 'Lithuania') 
    Country.create(:iso => 'LU', :name => 'Luxembourg') 
    Country.create(:iso => 'MO', :name => 'Macao') 
    Country.create(:iso => 'MK', :name => 'Macedonia, the Former Yugoslav Republic of') 
    Country.create(:iso => 'MG', :name => 'Madagascar') 
    Country.create(:iso => 'MW', :name => 'Malawi') 
    Country.create(:iso => 'MY', :name => 'Malaysia') 
    Country.create(:iso => 'MV', :name => 'Maldives') 
    Country.create(:iso => 'ML', :name => 'Mali') 
    Country.create(:iso => 'MT', :name => 'Malta') 
    Country.create(:iso => 'MH', :name => 'Marshall Islands') 
    Country.create(:iso => 'MQ', :name => 'Martinique') 
    Country.create(:iso => 'MR', :name => 'Mauritania') 
    Country.create(:iso => 'MU', :name => 'Mauritius') 
    Country.create(:iso => 'MX', :name => 'Mexico') 
    Country.create(:iso => 'FM', :name => 'Micronesia, Federated States of') 
    Country.create(:iso => 'MD', :name => 'Moldova, Republic of') 
    Country.create(:iso => 'MC', :name => 'Monaco') 
    Country.create(:iso => 'MN', :name => 'Mongolia') 
    Country.create(:iso => 'MS', :name => 'Montserrat') 
    Country.create(:iso => 'MA', :name => 'Morocco') 
    Country.create(:iso => 'MZ', :name => 'Mozambique') 
    Country.create(:iso => 'MM', :name => 'Myanmar') 
    Country.create(:iso => 'NA', :name => 'Namibia') 
    Country.create(:iso => 'NR', :name => 'Nauru') 
    Country.create(:iso => 'NP', :name => 'Nepal') 
    Country.create(:iso => 'NL', :name => 'Netherlands') 
    Country.create(:iso => 'AN', :name => 'Netherlands Antilles') 
    Country.create(:iso => 'NC', :name => 'New Caledonia') 
    Country.create(:iso => 'NZ', :name => 'New Zealand') 
    Country.create(:iso => 'NI', :name => 'Nicaragua') 
    Country.create(:iso => 'NE', :name => 'Niger') 
    Country.create(:iso => 'NG', :name => 'Nigeria') 
    Country.create(:iso => 'NU', :name => 'Niue') 
    Country.create(:iso => 'NF', :name => 'Norfolk Island') 
    Country.create(:iso => 'MP', :name => 'Northern Mariana Islands') 
    Country.create(:iso => 'NO', :name => 'Norway') 
    Country.create(:iso => 'OM', :name => 'Oman') 
    Country.create(:iso => 'PK', :name => 'Pakistan') 
    Country.create(:iso => 'PW', :name => 'Palau') 
    Country.create(:iso => 'PA', :name => 'Panama') 
    Country.create(:iso => 'PG', :name => 'Papua New Guinea') 
    Country.create(:iso => 'PY', :name => 'Paraguay') 
    Country.create(:iso => 'PE', :name => 'Peru') 
    Country.create(:iso => 'PH', :name => 'Philippines') 
    Country.create(:iso => 'PN', :name => 'Pitcairn') 
    Country.create(:iso => 'PL', :name => 'Poland') 
    Country.create(:iso => 'PT', :name => 'Portugal') 
    Country.create(:iso => 'PR', :name => 'Puerto Rico') 
    Country.create(:iso => 'QA', :name => 'Qatar') 
    Country.create(:iso => 'RE', :name => 'Reunion') 
    Country.create(:iso => 'RO', :name => 'Romania') 
    Country.create(:iso => 'RU', :name => 'Russian Federation') 
    Country.create(:iso => 'RW', :name => 'Rwanda') 
    Country.create(:iso => 'SH', :name => 'Saint Helena') 
    Country.create(:iso => 'KN', :name => 'Saint Kitts and Nevis') 
    Country.create(:iso => 'LC', :name => 'Saint Lucia') 
    Country.create(:iso => 'PM', :name => 'Saint Pierre and Miquelon') 
    Country.create(:iso => 'VC', :name => 'Saint Vincent and the Grenadines') 
    Country.create(:iso => 'WS', :name => 'Samoa') 
    Country.create(:iso => 'SM', :name => 'San Marino') 
    Country.create(:iso => 'ST', :name => 'Sao Tome and Principe') 
    Country.create(:iso => 'SA', :name => 'Saudi Arabia') 
    Country.create(:iso => 'SN', :name => 'Senegal') 
    Country.create(:iso => 'SC', :name => 'Seychelles') 
    Country.create(:iso => 'SL', :name => 'Sierra Leone') 
    Country.create(:iso => 'SG', :name => 'Singapore') 
    Country.create(:iso => 'SK', :name => 'Slovakia') 
    Country.create(:iso => 'SI', :name => 'Slovenia') 
    Country.create(:iso => 'SB', :name => 'Solomon Islands') 
    Country.create(:iso => 'SO', :name => 'Somalia') 
    Country.create(:iso => 'ZA', :name => 'South Africa') 
    Country.create(:iso => 'ES', :name => 'Spain') 
    Country.create(:iso => 'LK', :name => 'Sri Lanka') 
    Country.create(:iso => 'SD', :name => 'Sudan') 
    Country.create(:iso => 'SR', :name => 'Suriname') 
    Country.create(:iso => 'SJ', :name => 'Svalbard and Jan Mayen') 
    Country.create(:iso => 'SZ', :name => 'Swaziland') 
    Country.create(:iso => 'SE', :name => 'Sweden') 
    Country.create(:iso => 'CH', :name => 'Switzerland') 
    Country.create(:iso => 'SY', :name => 'Syrian Arab Republic') 
    Country.create(:iso => 'TW', :name => 'Taiwan, Province of China') 
    Country.create(:iso => 'TJ', :name => 'Tajikistan') 
    Country.create(:iso => 'TZ', :name => 'Tanzania, United Republic of') 
    Country.create(:iso => 'TH', :name => 'Thailand') 
    Country.create(:iso => 'TG', :name => 'Togo') 
    Country.create(:iso => 'TK', :name => 'Tokelau') 
    Country.create(:iso => 'TO', :name => 'Tonga') 
    Country.create(:iso => 'TT', :name => 'Trinidad and Tobago') 
    Country.create(:iso => 'TN', :name => 'Tunisia') 
    Country.create(:iso => 'TR', :name => 'Turkey') 
    Country.create(:iso => 'TM', :name => 'Turkmenistan') 
    Country.create(:iso => 'TC', :name => 'Turks and Caicos Islands') 
    Country.create(:iso => 'TV', :name => 'Tuvalu') 
    Country.create(:iso => 'UG', :name => 'Uganda') 
    Country.create(:iso => 'UA', :name => 'Ukraine') 
    Country.create(:iso => 'AE', :name => 'United Arab Emirates') 
    Country.create(:iso => 'GB', :name => 'United Kingdom') 
    Country.create(:iso => 'US', :name => 'United States') 
    Country.create(:iso => 'UY', :name => 'Uruguay') 
    Country.create(:iso => 'UZ', :name => 'Uzbekistan') 
    Country.create(:iso => 'VU', :name => 'Vanuatu') 
    Country.create(:iso => 'VE', :name => 'Venezuela') 
    Country.create(:iso => 'VN', :name => 'Viet Nam') 
    Country.create(:iso => 'VG', :name => 'Virgin Islands, British') 
    Country.create(:iso => 'VI', :name => 'Virgin Islands, U.s.') 
    Country.create(:iso => 'WF', :name => 'Wallis and Futuna') 
    Country.create(:iso => 'EH', :name => 'Western Sahara') 
    Country.create(:iso => 'YE', :name => 'Yemen') 
    Country.create(:iso => 'ZM', :name => 'Zambia') 
    Country.create(:iso => 'ZW', :name => 'Zimbabwe') 

  end
end
